/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureconverter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author MCENDROWSKI
 */
public class TemperatureConverterWindow extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TemperatureConverterWindow
     */
    public TemperatureConverterWindow() {
        initComponents();
                //Group the radio buttons.
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(rbtCelsiusToFahrenheit);
        buttonGroup.add(rbtFahrenheitToCelsius);
        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemperaturePrompt = new javax.swing.JLabel();
        txfTemperature = new javax.swing.JTextField();
        btnConvertTemperature = new javax.swing.JButton();
        lblShowConvertedTemperature = new javax.swing.JLabel();
        pnlButtonGroup = new javax.swing.JPanel();
        rbtFahrenheitToCelsius = new javax.swing.JRadioButton();
        rbtCelsiusToFahrenheit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemperaturePrompt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTemperaturePrompt.setText("Fahrenheit temperature:");
        lblTemperaturePrompt.setToolTipText("");

        txfTemperature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnConvertTemperature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConvertTemperature.setText("convert temperature");
        btnConvertTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertTemperatureActionPerformed(evt);
            }
        });

        lblShowConvertedTemperature.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblShowConvertedTemperature.setText("Celsius temperature: ");
        lblShowConvertedTemperature.setToolTipText("");

        pnlButtonGroup.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 3, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlButtonGroup.setName(""); // NOI18N

        rbtFahrenheitToCelsius.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtFahrenheitToCelsius.setText("Fahrenheit to Celsius");
        rbtFahrenheitToCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFahrenheitToCelsiusActionPerformed(evt);
            }
        });

        rbtCelsiusToFahrenheit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtCelsiusToFahrenheit.setText("Celsius to Fahrenheit");
        rbtCelsiusToFahrenheit.setToolTipText("");
        rbtCelsiusToFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCelsiusToFahrenheitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonGroupLayout = new javax.swing.GroupLayout(pnlButtonGroup);
        pnlButtonGroup.setLayout(pnlButtonGroupLayout);
        pnlButtonGroupLayout.setHorizontalGroup(
            pnlButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonGroupLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtCelsiusToFahrenheit)
                    .addComponent(rbtFahrenheitToCelsius))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnlButtonGroupLayout.setVerticalGroup(
            pnlButtonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonGroupLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbtFahrenheitToCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtCelsiusToFahrenheit)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        rbtFahrenheitToCelsius.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblShowConvertedTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConvertTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTemperaturePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                                .addComponent(txfTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlButtonGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pnlButtonGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnConvertTemperature)
                .addGap(28, 28, 28)
                .addComponent(lblShowConvertedTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertTemperatureActionPerformed
        
        
                     //Group the radio buttons.
       
 
//        //Register a listener for the radio buttons.
//        rbtCelsiusToFahrenheit.addActionListener(this);
//        
//        rbtFahrenheitToCelsius.addActionListener(this);
        
        double temperature;
        double convertedTemperature;

        if (rbtFahrenheitToCelsius.isSelected()){
        
//            lblTemperaturePrompt.setText("Fahrenheit temperature: ");
            
            temperature = Double.parseDouble(txfTemperature.getText());       
        
        convertedTemperature = (temperature-32)*5/9;
        lblShowConvertedTemperature.setText("Celsius temperature: "+convertedTemperature);
        
        }
        else {
//            lblTemperaturePrompt.setText("Celsius temperature: ");
            temperature = Double.parseDouble(txfTemperature.getText());       
        
        convertedTemperature = (temperature*9/5+32);
        lblShowConvertedTemperature.setText("Fahrenheit temperature: "+convertedTemperature);
        }
              
        
        
        
        
    }//GEN-LAST:event_btnConvertTemperatureActionPerformed

    private void rbtFahrenheitToCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFahrenheitToCelsiusActionPerformed
       lblTemperaturePrompt.setText("Fahrenheit temperature: ");
       lblShowConvertedTemperature.setText("Celsius temperature:");
       
    }//GEN-LAST:event_rbtFahrenheitToCelsiusActionPerformed

    private void rbtCelsiusToFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCelsiusToFahrenheitActionPerformed
 lblTemperaturePrompt.setText("Celsius temperature: ");
       lblShowConvertedTemperature.setText("Fahrenheit temperature:");
        
// TODO add your handling code here:
    }//GEN-LAST:event_rbtCelsiusToFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TemperatureConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TemperatureConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TemperatureConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TemperatureConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TemperatureConverterWindow().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertTemperature;
    private javax.swing.JLabel lblShowConvertedTemperature;
    private javax.swing.JLabel lblTemperaturePrompt;
    private javax.swing.JPanel pnlButtonGroup;
    private javax.swing.JRadioButton rbtCelsiusToFahrenheit;
    private javax.swing.JRadioButton rbtFahrenheitToCelsius;
    private javax.swing.JTextField txfTemperature;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("You selected one button.");
    }
}
